cargo-features = ["edition2021"]

[package]
name = "pn"
version = "0.0.0"
authors = ["Zoltan Kochan <z@kochan.io>"]
edition = "2021"

[dependencies]
serde_json="1.0"
serde = { version = "1.0", features = ["derive"] }
ansi_term = "0.12.1"
derive_more = "0.99.14"
pipe-trait = "0.3.2"
